---
# Ansible playbook to backup device configuration
# Usage: ansible-playbook -i inventory.yml backup_config.yml -e "target_host=device_name backup_file=path/to/backup.cfg"

- name: Backup Device Configuration
  hosts: "{{ target_host }}"
  gather_facts: no
  
  tasks:
    - name: Backup Cisco IOS configuration
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ backup_file | basename }}"
          dir_path: "{{ backup_file | dirname }}"
      when: ansible_network_os == 'ios' or ansible_network_os == 'cisco_ios'
      register: backup_result
    
    - name: Backup Juniper configuration
      junos_config:
        backup: yes
        backup_options:
          filename: "{{ backup_file | basename }}"
          dir_path: "{{ backup_file | dirname }}"
      when: ansible_network_os == 'junos'
      register: backup_result
    
    - name: Backup Arista EOS configuration
      eos_config:
        backup: yes
        backup_options:
          filename: "{{ backup_file | basename }}"
          dir_path: "{{ backup_file | dirname }}"
      when: ansible_network_os == 'eos' or ansible_network_os == 'arista_eos'
      register: backup_result
    
    - name: Set success flag
      set_fact:
        backup_success: true
      when: backup_result is defined and backup_result.changed | default(false)
    
    - name: Set result
      set_fact:
        ansible_result:
          success: "{{ backup_success | default(false) }}"
          backup_path: "{{ backup_file }}"
          changed: "{{ backup_result.changed | default(false) }}"